Switch to bash
Build process fails because of "Illegal option -o pipefail" error in
bin/compile script.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,10 +1,10 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 # Perform the transformation steps on the app.
 #
 # Usage: bin/compile BUILD_DIR CACHE_DIR ENV_DIR
 
 set -o errexit    # always exit on error
-set -o pipefail   # don"t ignore exit codes when piping output
+set -o pipefail   # don't ignore exit codes when piping output
 set -o nounset    # fail on unset variables
 unset GIT_DIR     # Avoid GIT_DIR leak from previous build steps
 
